### ISSUE TITLE
Should the final ToR contain only courses passed during the mobility?

### ISSUE THREAD

**Issue by wrygiel** [erasmus-without-paper/ewp-specs-mobility-flowcharts#4]
@erasmus-without-paper/norway 
@erasmus-without-paper/sweden 
@janinamincer-daszkiewicz 
1. Should the final ToR (the one exchanged after the mobility ends) contain only these courses which were passed **during the mobility**?
2. Or, should it contain **all courses ever studied** by the student in the receiving HEI?

I guess that the safest option would be to follow the current business process. So, the question is - how it is done currently (on paper)?

**Comment by georgschermann** [comment]
Differs from HEI to HEi.
Most common practice here is to include all courses referring to the LA regardless of passed or not. Sometimes even not passed courses lead to a positive grade from the sending HEI. Some have requirements of minimal ECTS attended, with sometimes financial consequences.

**Comment by vickalaser** [comment]
The ECTS guideline is for all courses studies to be recorded on the LA and to appear on the TOR of the Host. These should then all be transferred to the TOR of the Home.

**Comment by wrygiel** [comment]
I'm designing input parameters for the Transcript of Records API just now.
- I believe that the safest input parameter would be `mobility_id` (as opposed to student ID). This way, if a students goes to the same receiving HEI two times, we will be able to fetch two separate ToRs (as opposed to two copies of the same ToR).
- The receiving institution will be required to include _at least_ these courses which were recorded on the LA. I don't think we can require _exactly_ the same courses, because not all LAs will contain course IDs. Such specification will allow the receiving institution to include _all_ courses in the response.
- Of course, we will also recommend for the receiving institution to include all courses the student has actually studied in the student's LA.

**Comment by janinamincer-daszkiewicz** [comment]
I would rather assume that host institution will not care much about LA and will issue transcript with courses taken - some of them will report only passed courses, some will report all taken courses. It is probably quite common that host institution signs LA but them forgets about it.

**Comment by wrygiel** [comment]
My current (draft) version of the [ToRs API](https://github.com/erasmus-without-paper/ewp-specs-api-tors) takes `mobility_id` parameters (as opposed to student IDs). If we decide that this API should always return full ToRs (not just parts of them), then I think we should use student IDs instead.

**Comment by wrygiel** [comment]
We talked about it briefly in Warsaw. We have concluded that it is okay for ToRs API to be dependent on Mobilities API, and take `mobility_id` parameters. ToRs from our use cases should always be related to mobility.
